name: Update .gitignore

on:
  push:
    branches:
      - test
      - release

jobs:
  update-gitignore:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add/update .gitignore
      run: |
        echo "# Ignore Jupyter notebook files" > .gitignore
        echo "*.ipynb" >> .gitignore
        echo "# Ignore HTML files" >> .gitignore
        echo "*.html" >> .gitignore
        echo "# Ignore __pycache__, .idea, and .ipynb_checkpoints directories" >> .gitignore
        echo "__pycache__/" >> .gitignore
        echo ".idea/" >> .gitignore
        echo ".ipynb_checkpoints/" >> .gitignore
        git diff --exit-code || (git add .gitignore && git commit -m "Update .gitignore for ${GITHUB_REF##*/}" && git push)
